// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAA_vZPHB-75KvJdrOtdmPJUHe0DKpqpmw',
    appId: '1:179855917763:web:d24a703481b277bab75876',
    messagingSenderId: '179855917763',
    projectId: 'crud-664c9',
    authDomain: 'crud-664c9.firebaseapp.com',
    storageBucket: 'crud-664c9.appspot.com',
    measurementId: 'G-N0P4TVYQHN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLvmx15Hey_cWoCwDS4D5ZsZ1eZoNCaYE',
    appId: '1:179855917763:android:230a0baf4916caa6b75876',
    messagingSenderId: '179855917763',
    projectId: 'crud-664c9',
    storageBucket: 'crud-664c9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCy8dnQcBqgRFGLnVjpUB8WV0XdS2iE35g',
    appId: '1:179855917763:ios:feaf54d7e4dc2b27b75876',
    messagingSenderId: '179855917763',
    projectId: 'crud-664c9',
    storageBucket: 'crud-664c9.appspot.com',
    iosBundleId: 'com.example.crud',
  );

}